esphome:
  name: yardgate
  friendly_name: YardGate
  platformio_options:
    upload_speed: 460800
    build_unflags: -Werror=all
    board_build.f_flash: 80000000L
    board_build.f_cpu: 240000000L
    # something is broken in the old (=current for esphome) platform version
    board_build.flash_mode: dio

external_components:
  - source: github://pr#6300
    components: [ cc1101 ]
  - source: github://buglloc/esphome-components
    components: [ pinky_winky ]

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80000000

# Enable logging
logger:

# поддержка Home Assistant
api:
  encryption:
    key: "DEADBEEF"

# и без OTA никуда
ota:
  - platform: esphome
    password: "deafbeef"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# обязательно настраиваем нормальный источник времени
time:
  - platform: homeassistant

# XIAO ESP32-S3 имеет встроеный диодик, нет повода не заиспользовать для статуса 
status_led:
  pin:
    number: GPIO21
    inverted: True

# включаем ESP32 BLE tracker, без него pinky_winky неоткуда брать информацию
esp32_ble_tracker:
  scan_parameters:
    interval: 50ms
    window: 30ms
    active: false
    continuous: true

# настройки SPI в соотв. с нашей схемой подключения CC1101
spi:
  clk_pin: GPIO8
  miso_pin: GPIO7
  mosi_pin: GPIO2

# настройки CC1101, нам важно переключить его на 330Mhz
cc1101:
  id: transceiver
  cs_pin: GPIO1
  bandwidth: 650
  frequency: 330000

# настройки PinkyWinky
pinky_winky:
  - id: bike_tracker
    mac_address: "D8:67:51:7C:F9:8C"
    secret: "SomeVerySecretSecret"

# RF передатчик, ESP32-S3 имеет два TX RMT (Remote Control) канала, используем первый
remote_transmitter:
  pin: GPIO9
  carrier_duty_percent: 100%
  rmt_channel: 0

# RF приемник, нам не важен, но пусть будет
# remote_receiver:
#   pin: GPIO4
#   dump:
#     - rc_switch
#   rmt_channel: 4
#   tolerance: 50%
#   buffer_size: 2kb
#   filter: 100us
#   idle: 4ms

# кнопка бикона
binary_sensor:
  - platform: pinky_winky
    id: bike_button
    input: bike_tracker
    name: "Bike tracker button"
    on_press:
      - button.press: gate

# батарейка бикона и сигнал wifi
sensor:
  - platform: pinky_winky
    input: bike_tracker
    battery_level:
      id: bike_battery
      name: "Bike tracker battery level"
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s

button:
  # кнопка сброса состояния
  - platform: template
    name: "[re]Bind bike tracker"
    on_press:
      - pinky_winky.reset:
          id: bike_tracker
  # кнопка управления воротами
  - platform: template
    name: "Gate"
    id: gate
    on_press:
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '0100011111111100101110101'
          protocol:
            pulse_length: 345
            sync: [1, 21]
            zero: [1, 3]
            one: [3, 1]
          repeat:
            times: 4
            wait_time: 0s

# удобно удалено порестартить при необходимости
switch:
  - platform: restart
    name: Restart

